version: '3.1'

services:
  db:
    image: postgres:12
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leaguedex
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 5051:8080
